"""
Java Source Concatenator
Merges all .java source files in a project into one text file
so the full codebase can be uploaded to Copilot in one go.

How to run:
  1. Set PROJECT_DIR below to your Java project folder
  2. Open Anaconda Prompt, cd to this script's folder, then run:
         python concat_java.py
  3. all_java_code.txt (or split part files) will be created in the same folder.
     Upload the file(s) to Copilot.

Uses Python standard library only — no extra packages needed.
"""

import sys
from pathlib import Path

# ==================== CONFIGURATION (edit here) ====================
PROJECT_DIR = r"C:\Users\YourName\path\to\java\project"   # <- change this
OUTPUT_FILE = "all_java_code.txt"

# Directories to skip (compiled output, dependencies, version history, etc.)
IGNORE_DIRS = {
    "target", "build", "bin", "out", "dist", "classes",
    ".git", ".idea", ".settings", ".gradle", ".mvn", "node_modules",
}

# Whether to include test code (files whose path contains "test").
# Set to False to help Copilot focus on business logic only.
INCLUDE_TESTS = True

# Number of output parts. Copilot allows up to 3 file uploads per conversation.
# 1 = single output file. If the file is too large, change to 2 or 3 to split evenly.
SPLIT_PARTS = 1
# ===================================================================

# If the total output exceeds this many characters, a warning is printed.
WARN_CHARS = 600_000


def read_text(path: Path) -> str:
    """Try multiple encodings to handle Chinese comments without errors."""
    for enc in ("utf-8-sig", "utf-8", "gbk", "latin-1"):
        try:
            return path.read_text(encoding=enc)
        except (UnicodeDecodeError, UnicodeError):
            continue
    return path.read_text(encoding="utf-8", errors="replace")


def is_test(rel: Path) -> bool:
    parts = [p.lower() for p in rel.parts]
    return any("test" in p for p in parts)


def main():
    root = Path(PROJECT_DIR)
    if not root.is_dir():
        print(f"Directory not found: {root}\nPlease update PROJECT_DIR at the top of this script.")
        sys.exit(1)

    files = []
    for p in sorted(root.rglob("*.java")):
        rel = p.relative_to(root)
        if any(part in IGNORE_DIRS for part in rel.parts):
            continue
        if not INCLUDE_TESTS and is_test(rel):
            continue
        files.append((rel, p))

    if not files:
        print("No .java files found. Please check that PROJECT_DIR points to the right folder.")
        sys.exit(1)

    # Build one text block per file, with a clear separator header
    blocks = []
    total_lines = 0
    for rel, p in files:
        text = read_text(p)
        total_lines += text.count("\n") + 1
        sep = "=" * 78
        block = (f"{sep}\n"
                 f"// FILE: {rel.as_posix()}\n"
                 f"{sep}\n"
                 f"{text}\n\n")
        blocks.append(block)

    full = "".join(blocks)
    total_chars = len(full)

    n = max(1, SPLIT_PARTS)
    if n == 1:
        outputs = {OUTPUT_FILE: full}
    else:
        # Split into n parts at file boundaries, balanced by character count
        target = total_chars / n
        parts, cur, cur_size = [], [], 0
        for b in blocks:
            if cur and cur_size + len(b) > target and len(parts) < n - 1:
                parts.append("".join(cur))
                cur, cur_size = [], 0
            cur.append(b)
            cur_size += len(b)
        if cur:
            parts.append("".join(cur))
        stem = Path(OUTPUT_FILE).stem
        suffix = Path(OUTPUT_FILE).suffix or ".txt"
        outputs = {f"{stem}_part{idx}{suffix}": txt
                   for idx, txt in enumerate(parts, start=1)}

    for name, content in outputs.items():
        header = (f"// Generated by concat_java.py\n"
                  f"// Project: {root.name}  |  {len(files)} Java file(s), "
                  f"{total_lines:,} lines total\n\n")
        Path(name).write_text(header + content, encoding="utf-8")

    print(f"Done! Merged {len(files)} Java file(s), "
          f"{total_lines:,} lines, {total_chars:,} characters.")
    for name in outputs:
        size_kb = Path(name).stat().st_size / 1024
        print(f"  - {name}  ({size_kb:,.0f} KB)")

    if n == 1 and total_chars > WARN_CHARS:
        print("\nWarning: the output file is large and Copilot may not read it all.")
        print("  Try setting SPLIT_PARTS to 2 or 3 and re-running,")
        print("  or set INCLUDE_TESTS = False to exclude test files.")


if __name__ == "__main__":
    main()
